### ISSUE TITLE
Unorganized/Unclear Sample Code

### ISSUE THREAD

**Issue by The5heepDev** [amzn/login-and-pay-with-amazon-sdk-php#10]
The instructions provided aren't very clear. Also, all the instructions for this are in several different places. They also use different methods for doing things, so you have to jump around to figure things out, and they aren't thoroughly explained. Please fix this as it could deter developers from using your service in the future.

**Comment by shrakuma** [comment]
Hi
Thank you for your feedback. Could you please elaborate on the issues you faced with the instructions and the methods,Which  parts of the sample demo was not clear.
With all the information that will be provided by you we can definitely take this up immediately to make  and incorporate the changes so as to  provide the best experience to our developer community

**Comment by The5heepDev** [comment]
I had issues on initiating the PHP. The only way I figured out how to was by finding a comment in the sample code that said 'ajax'. You should provide a sample jQuery ajax request developers can use. You should do the same for the rest of the PHP code. The site https://payments.amazon.com/documentation/lpwa/201749840 uses PHP to get the customer information, whereas the demo uses an asynchronous authRequest to check if the user is logged in and get the customer information. The payments.amazon.com guide says "A client must use an access token to retrieve customer profile data", but using the JavaScript method works perfectly fine, and is much less complicated. You should also put how your directories and files should be set up, and which ones are required for what.

**Comment by The5heepDev** [comment]
@shrakuma Have you made any progress on this?

**Comment by shrakuma** [comment]
Thanks for the above feedback.  We have included this as part of our sprint planning,I will be uploading a sample(s) by the end of next week which will showcase an end to end simple checkout example.

Also when you are referring to "The site https://payments.amazon.com/documentation/lpwa/201749840 uses PHP to get the customer information, whereas the demo uses an asynchronous authRequest to check if the user is logged in and get the customer information"

Are you referring to the method as described in the readme https://github.com/amzn/login-and-pay-with-amazon-sdk-php#obtain-profile-information-getuserinfo-method
this method makes it easy as you would just need to send the access token from the URL to this method to get the output.

**Comment by The5heepDev** [comment]
https://payments.amazon.com/documentation/lpwa/201749840#201749970
Uses the getUserInfo method also

But the site:
https://amzn.github.io/login-and-pay-with-amazon-sdk-samples/login_and_pay/lpa-login-cart.html
Uses javascript to get the user info.

**Comment by shrakuma** [comment]
I agree that the JavaScript method is very useful. In the case of the SDK we wanted to have an inbuilt and an easy function that would do the same in the language of the SDK and provide the appropriate output.

**Comment by islandskater43** [comment]
It's also important to understand that the JavaScript methods are very helpful, but shouldn't be used in certain scenarios such as during a login flow. You wouldn't want to use the JS method to retrieve the Amazon CustomerId, and then pass that back to the backend, where an end user could alter the value in transit. You could however use it to pre-populate a field in a checkout flow for Buyer Name. 

Do you think clarifying the use case of the two different methods, and adding information on the JS functionality to the documentation (https://payments.amazon.com/documentation/lpwa/201749840#201749970) would help clear up the confusion?

**Comment by The5heepDev** [comment]
@islandskater43 I believe that would clear up confusion. I am only using it for frontend calculations, such as getting the zip code for the shipping cost. Anything else is handled by the backend php.

**Comment by The5heepDev** [comment]
@shrakuma How do you get the full address of the user with PHP? I couldn't find anything in the docs.

**Comment by shrakuma** [comment]
sample has been added to the https://github.com/amzn/login-and-pay-with-amazon-sdk-samples
