### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by The5heepDev** [amzn/login-and-pay-with-amazon-sdk-php#11]
Could you add a way to add 'custom' charges? For example above the charge amount in the email:
![screenshot from 2015-07-12 20-57-53](https://cloud.githubusercontent.com/assets/8976745/8640982/d50f3792-28d8-11e5-8188-9303e7978c96.png)
make it so that we can have something like:

<div>
Cost: ..
<br>
Shipping: ...
<hr>
<strong>Total: ...</strong>
</div>

Currently there is only the amount value we can change.

**Comment by shrakuma** [comment]
Hi
is this referring to the charge convenience function which takes amount as the parameter. Is it in this convenience method you are requesting that the shipping , other costs be added?

**Comment by The5heepDev** [comment]
Yes. You should be able to add custom costs (ie. shipping) through a string.

**Comment by shrakuma** [comment]
Unfortunately Login and Pay With Amazon design is done in a way to not take in shipping and tax calculation. I would recommend saving these information in your database during your checkout  and associate it to the Amazon Order Reference ID.
