### ISSUE TITLE
Update composer package at packagist.org to unbreak IPN handling

### ISSUE THREAD

**Issue by ejegg** [amzn/login-and-pay-with-amazon-sdk-php#15]
At https://packagist.org/packages/amzn/login-and-pay-with-amazon-sdk-php , v1.0 still points to rev 3bf17e802dc6913aa97f1afdaf26a08480f670d0 from back in April.  Please update it to point to 'removed unused remaining IPN fields' so users with the default version installed don't get 'undefined index IsSample' errors.

**Comment by shrakuma** [comment]
Thank you. I will update the same

**Comment by shrakuma** [comment]
updated to remove the unused releases and dev-master is the main resource for download from packagist. 
@ejegg could you please confirm if the fix is good.

**Comment by kzap** [comment]
can you pls use tags so we can stick to versions and not risk using a version with a breaking change... noone likes breaking payments,

just dont reuse the same tag
