### ISSUE TITLE
The "Maximum number of retry attempts reached" exception produces a lot of warnings

### ISSUE THREAD

**Issue by evgenius** [amzn/login-and-pay-with-amazon-sdk-php#2]
The constructor of OffAmazonPaymentsService_Exception assumes the array passed as a parameter contains all fields. But actually when the exception is thrown only Message and StatusCode are provided.
This happens in several places.

As a result we get a lot of warnings:
```
E_NOTICE Undefined index: ErrorType
E_NOTICE Undefined index: RequestId
E_NOTICE Undefined index: XML
E_NOTICE Undefined index: ResponseHeaderMetadata
```

**Comment by shrakuma** [comment]
Hi 
We are reforming a new PHP SDK. it's under the same repo called the phoenix branch. The code is not released as the changes are still going through. Please take a look at it and let us now your comments and also if you see any potential bugs
thank you
