### ISSUE TITLE
Does this work with marketplace? 

### ISSUE THREAD

**Issue by HallofFamer** [amzn/login-and-pay-with-amazon-sdk-php#21]
Well we want to build a website in which we are the a third party marketplace provider. Buyers buy goods from other sellers, and we collect about 2-3% transaction fee each time an invoice is paid. I wonder, does this amazon login-and-pay SDK handles this marketplace scenario? I do notice that there are both a merchant ID and a seller ID, so I guess these two can be different?

**Comment by shrakuma** [comment]
Yes, the SDK incorporates Marketplace scenario. The merchant ID and Seller ID are the same. 

# Account requirements for Marketplace scenario
1. Your Login and Pay With Amazon account in seller central should be marked as Marketplace. For this please provide me your Merchant ID. I will get it marked as Marketplace accordingly

In API calls such as Authorize and Capture there is a field called 'provider_credit_details'	 => array()
Authorize API call -> https://github.com/amzn/login-and-pay-with-amazon-sdk-php/blob/master/PayWithAmazon/Client.php#L672
Capture API call -> https://github.com/amzn/login-and-pay-with-amazon-sdk-php/blob/master/PayWithAmazon/Client.php#L735
You can send this input in either of these API calls.

**Case 1: If the 'provider_credit_details' is sent in Authorize API call**
Authorize API call has a parameter called as capture_now which is a boolean value that takes true or false. This has to be set to true if 'provider_credit_details' is passed 

**Case 2: If the 'provider_credit_details' is sent in Capture API call**
Here you can simply pass the 'provider_credit_details'  array

**How to pass the Provider credit details**
Following is an example Capture API call (assuming the Client class object is instantiated according to the read-me -> https://github.com/amzn/login-and-pay-with-amazon-sdk-php/blob/master/README.md)
$requestParameters = array();

// Amazon Authorization ID will be provided in the response of the Authorize API call
$requestParameters['amazon_authorization_id'] = 'Amazon Authorization ID';

// Here merchant_id value will be your marketplace on-boarded merchant's Merchant ID
$requestParameters['merchant_id'] = 'ONBOARDED_MERCHANTID';
$requestParameters['capture_amount'] = 'capture amount'; // example '100'

$providerCredit  =  array();
$providerDetailsarray = array('provider_id' => 'YOUR_MERCHANT_ID',
                                       'credit_amount' => 'CREDIT_AMOUNT', // transaction fee example '10'
                                       'currency_code' => 'USD');
array_push($providerCredit,$providerDetailsarray);

$requestParameters['currency_code'] = 'USD';
$requestParameters['capture_reference_id'] = "some unique string";
$requestParameters['seller_capture_note'] = 'sample capture note';
$requestParameters['provider_credit_details'] = $providerCredit;
$requestParameters['mws_auth_token'] = 'MWS Auth Token of your on-boarded merchant';

$response = $client->Capture($requestParameters);

print_r($response->toXml());
print_r($response->toJson());
print_r($response->toArray());
----------------------------------------------------------------------------------------------------------------------------------
**Other inputs needed**
1. MWS auth token of the onboarded merchant 
2. Merchant ID of the onboarded merchant.

Once your account is marked as a Marketplace you will get a view in Seller Central where in you can generate a exclusive link that you can provide to your merchants who want to be onboarded to your marketplace. While generating this link you should provide a return URL to your domain where they would be redirected to once they complete the process. 

At the final step of the process  they will be redirected to the return URL . In this return URL there will be MWS auth token and Merchant ID as query/url parameters. you will have a script in this page that will grab these parameters and save it in your DB.
