### ISSUE TITLE
 The requested package amzn/login-and-pay-with-amazon-sdk-php could not be found in any version, there may be a typo in the package name.

### ISSUE THREAD

**Issue by aligajani** [amzn/login-and-pay-with-amazon-sdk-php#23]

**Comment by aligajani** [comment]
@danielneu

**Comment by danielneu** [comment]
Hi Ali,

can you elaborate on this? 

Best wishes
Daniel

**Comment by danielneu** [comment]
Got it,

you are referring to composer, please give more details next time.

Try:

 "require": {
        "amzn/login-and-pay-with-amazon-sdk-php": "*@dev"
    }

**Comment by aligajani** [comment]
Hey Daniel,

Thanks man. Would be useful to update the documentation to mention this there as well.

**Comment by danielneu** [comment]
Agreed.

Created #24 for this.

Resolving.

~Daniel
