### ISSUE TITLE
Ensure that the received SNS IP address is from an Amazon AWS IP.

### ISSUE THREAD

**Issue by bmeynell** [amzn/login-and-pay-with-amazon-sdk-php#25]
From https://payments.amazon.com/documentation/apireference/201757720, section *"Secure IPN processing"*:

> You must ensure that the received SNS IP address is from an Amazon AWS IP. To do so, parse the list of AWS public IP address ranges and make sure that the received IP address is within one of those ranges.

> The list of AWS public IP address ranges is available in JSON form at https://ip-ranges.amazonaws.com/ip-ranges.json. The information in this file is generated from Amazon's internal system-of-record and is authoritative. It changes several times per week and you should poll accordingly.

**Comment by bmeynell** [comment]
In the last day or two Amazon removed the text cited above from their documentation. I've contacted Seller Support as to why. Will update here when I find out.

**Comment by dbrent-amazon** [comment]
Hello, we validate the certificate and make sure it comes from a valid SNS endpoint in the SDKs so IP validation shouldn't be needed. I am not sure why it was removed from the doc, however. I'll do some research.

**Comment by bmeynell** [comment]
> Hello, we validate the certificate and make sure it comes from a valid SNS endpoint in the SDKs

Where, exactly does that happen in the SDK? I looked, but couldn't find. Amazon also states that their ips "change frequently" so currently we're polling their ip list for every IPN request since it's the only way we know of to ensure we're completely up-to-date and don't deny based on an old ip-rule.

**Comment by dbrent-amazon** [comment]
Hello, I inadvertently deleted my last comment while trying to edit. I do see what you are talking about. I am speaking with some teams internally and will try to provide a response.

**Comment by samir-khoja** [comment]
Thanks again for your suggestion! Please see validation changes in version 2.0.1.
