### ISSUE TITLE
PHP7 should be supported

### ISSUE THREAD

**Issue by petrkotek** [amzn/login-and-pay-with-amazon-sdk-php#37]
People will be more & more interested in PHP7 support (I believe there's no need to mention the reasons/benefits).

Would it be possible to update us about PHP7 support matter here?
- what are currently known issues? (i checked the codebase with `php7cc` tool and it didn't find any issues, but that doesn't necessarily mean that everything works fine)
- when will that get fixed? timeline?
- how can community help to have it faster?

Thanks in advance for your response.

**Comment by petrkotek** [comment]
ping @islandskater43 would you be able to clarify reason for https://github.com/amzn/login-and-pay-with-amazon-sdk-php/commit/a30121ec42e9678940f783dc2ee87782063ce69f? Thanks!

/cc @samir-khoja @dbrent-amazon

**Comment by islandskater43** [comment]
@petrkotek - We had multiple people reaching out regarding php7 support. The readme update was to callout php7 support has not yet been confirmed on the SDK. Our team is working to validate and should be able to update the SDK soon.

**Comment by islandskater43** [comment]
The SDK has been verified working with PHP 7. https://github.com/amzn/login-and-pay-with-amazon-sdk-php/commit/596efaa1518dbfaffbbc41b130f0a13ed5330a99

**Comment by petrkotek** [comment]
fantastic, thanks guys!
